version: "3"
services:
  bookmeter-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./db:/app/instance
      - ./logs:/app/logs
